
platform :ios, '13.0'

target 'Demo' do
source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  pod 'ConnectWalletConnectAdapter', '0.1.40'
  pod 'ConnectEVMAdapter', '0.1.41'
  pod 'ConnectSolanaAdapter', '0.1.41'
  pod 'ConnectPhantomAdapter', '0.1.41'
  pod 'ParticleConnect', '0.1.41'
  pod 'ConnectCommon', '0.1.41'
  
  pod 'ParticleWalletAPI', '0.9.0'
  pod 'ParticleNetworkBase', '0.9.0'
  pod 'ParticleAuthService', '0.9.0'
  
  pod 'SnapKit'

end


post_install do |installer|
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end

  # This is necessary for Xcode 14, because it signs resource bundles by default
  # when building for devices.
  installer.target_installation_results.pod_target_installation_results
  .each do |pod_name, target_installation_result|
    target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
      resource_bundle_target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
