
platform :ios, '13.0'

target 'Demo' do
source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  pod 'ConnectWalletConnectAdapter', '0.1.26.1'
  pod 'ConnectEVMAdapter', '0.1.26.1'
  pod 'ConnectSolanaAdapter', '0.1.26.1'
  pod 'ConnectPhantomAdapter', '0.1.26.1'
  pod 'ParticleConnect', '0.1.26.1'
  pod 'ConnectCommon', '0.1.26.1'
  
  pod 'ParticleWalletAPI', '0.7.19.1'
  pod 'ParticleNetworkBase', '0.7.19.1'
  pod 'ParticleAuthService', '0.7.19.1'
  
  pod 'SnapKit'

end


post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings["ARCHS[sdk=iphonesimulator*]"] = "x86_64"
    config.build_settings["ARCHS[sdk=iphoneos*]"] = "arm64"
  end
end
